### ISSUE TITLE
feature request: module to drain node(s)

### ISSUE THREAD

**Issue by avorima** [ansible-collections/kubernetes.core#107]
##### SUMMARY

Currenty I'm using a `command` with kubectl to drain node(s). It is technically possible to implement this via `k8s` and `k8s_info` by listing all pods on the given node and then deleting them. I would prefer to be able to use the eviction API though, which is what `kubectl drain` tries to do before falling back to deletion, as well as some of the ways that eviction can be tweaked using `kubectl drain`.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by gravesm** [comment]
A new module for draining a node has been added in #141. Thanks for the suggestion @avorima.
