### ISSUE TITLE
Invalid kube-config after upgrade to kubernetes.core

### ISSUE THREAD

**Issue by ulrichSchreiner** [ansible-collections/kubernetes.core#145]
hi,

i use the ansible operator sdk to build k8s operators with ansible.  when developing you can start the operator locally. i have a `KUBECONFIG` environment file which points to my minikube and then i start the operator with `ansible-operator run`. 

when using the following requirement:
~~~
  - name: community.kubernetes
    version: "==1.2.1"
~~~

everything works. you can update the CRD and the operator starts to invoke the playbook/role to update the cluster ressources.

now i tried to update
~~~
 - name: kubernetes.core
   version: ">=2.0.2"
 - name: cloud.common
   version: ">=2.0.3"
~~~

everything looks good first; when the operator starts it executes the playbook and everything works great. but when a CRD is updated, the operator tries to execute the playbook because it watches the CRD and then the first tasks crashes:
~~~
...
Including module_utils file ansible_collections/kubernetes/core/plugins/module_utils/common.py
Including module_utils file ansible/module_utils/common/dict_transformations.py
Including module_utils file ansible_collections/kubernetes/core/plugins/module_utils/apply.py
Including module_utils file ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py
Including module_utils file ansible_collections/kubernetes/core/plugins/module_utils/exceptions.py
Including module_utils file ansible_collections/kubernetes/core/plugins/module_utils/hashes.py
Including module_utils file ansible_collections/kubernetes/core/plugins/module_utils/k8sdynamicclient.py
Using module file /root/.ansible/collections/ansible_collections/kubernetes/core/plugins/modules/k8s_cluster_info.py
<localhost> PUT /root/.ansible/tmp/ansible-local-4545_vmrx2us/tmpq1itftjy TO /root/.ansible/tmp/ansible-tmp-1624457675.498881-4599-214522123450534/AnsiballZ_k8s_cluster_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1624457675.498881-4599-214522123450534/ /root/.ansible/tmp/ansible-tmp-1624457675.498881-4599-214522123450534/AnsiballZ_k8s_cluster_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1624457675.498881-4599-214522123450534/AnsiballZ_k8s_cluster_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1624457675.498881-4599-214522123450534/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
  "changed": false,
  "invocation": {
    "module_args": {
      "api_key": null,
      "ca_cert": null,
      "client_cert": null,
      "client_key": null,
      "context": null,
      "host": null,
      "invalidate_cache": true,
      "kubeconfig": null,
      "password": null,
      "persist_config": null,
      "proxy": null,
      "proxy_headers": null,
      "username": null,
      "validate_certs": null
    }
  },
  "msg": "Failed to load kubeconfig due to Invalid kube-config file. No configuration found."
}
~~~
(the `/root` path is because i execute the whole thing in a container).

and now .... it becomes very strange. the operator tries to reconcile again and again and after a while (lets say after 10 errors) it seems to be stuck, but after a while the operator tries again an automatic reconcilation and then it works! i did not do anything.

when i open another shell in the container i see a process with a `turbo.server`. any chance to see where the problem is? as i said, i have a KUBECONFIG environment which points to a correct configuration. it looks like the config is not passed to subprocesses  in combination with a race condition.

i'm not sure if this has a relation to #56 ... the error message is the same.

**Comment by gravesm** [comment]
@ulrichSchreiner This is due to a bug in cloud.common. We have temporarily removed cloud.common as a dependency until we can sort out the underlying issues. If you upgrade to to kubernetes.core 2.1.1 things should be working again.
