### ISSUE TITLE
Document and test breaking change in k8s_cluster_info and provide porting guidance

### ISSUE THREAD

**Issue by tima** [ansible-collections/kubernetes.core#15]
##### SUMMARY

The PR ansible-collections/community.kubernetes#389 introduces a breaking change to address the problems introduced in issue ansible-collections/community.kubernetes#380. This needs to be called out in the documentation. Further, [as noted here](https://github.com/ansible-collections/community.kubernetes/pull/389#issuecomment-799404473), current testing of this module is inadequate and did not pickup the original issue or the breaking change that was submitted and needs to be addressed as part of this.

##### ISSUE TYPE
- Documentation

##### COMPONENT NAME

k8s_cluster_info

**Comment by gravesm** [comment]
@tima Is there a specific way we have of documenting breaking changes?

**Comment by Akasurde** [comment]
@gravesm Do you mean `breaking_changes` in the changelog entry?

**Comment by gravesm** [comment]
> This needs to be called out in the documentation.

@Akasurde  I guess I'm just wondering if there's some kind of standardized way to do this in the documentation, in addition to the changelog entry.
