### ISSUE TITLE
Add option to set version for helm_plugin

### ISSUE THREAD

**Issue by rendhalver** [ansible-collections/kubernetes.core#157]
##### SUMMARY

Add option to set version of plugin to install

When you install helm plugins we can set a version of the plgin to install like so:
`helm plugin install --version 0.8.0 https://github.com/helm/helm-2to3`
We should add this option so we can keep those plugins updated as required.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

helm_plugin

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Akasurde** [comment]
@rendhalver Thanks for reporting this feature.
