### ISSUE TITLE
ERROR! couldn't resolve module/action 'community.kubernetes.k8s'

### ISSUE THREAD

**Issue by amin224** [ansible-collections/kubernetes.core#159]
ISSUE TYPE

- Bug Report

COMPONENT NAME

- Community.kubernetes.k8s

SUMMARY

I am trying to use the community.kubernetes.k8s module for my ansible-playbook but I am unable to run it, I believe ansible is not able to find the module. I've tried many attempts from various sources to solve this issue.

ENVIRONMENT

-  ansible --version
```
ansible 2.9.6
  config file = /home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
```

- Operating System: Ubuntu 20.04

- ansible-galaxy collection install community.kubernetes

- collections:
    - name: community.kubernetes
      version: 2.0.0

##### COLLECTION VERSION

```
ansible-galaxy collection list community.kubernetes
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

##### CONFIGURATION

```
COLLECTIONS_PATHS(/home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/ansible.cfg) = ['/home/user/.ansible/collections/ansible_collections']
DEFAULT_HOST_LIST(/home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/ansible.cfg) = ['/home/user/Desktop/Kubernetes/ansible-Examples/deployment>
```

STEPS TO REPRODUCE

ansible-playbook main.yml --ask-become-pass -vvv

```
ansible-playbook 2.9.6
  config file = /home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
Using /home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/ansible.cfg as config file
BECOME password: 
host_list declined parsing /home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/inventory.yml as it did not pass its verify_file() method
Parsed /home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/inventory.yml inventory source with ini plugin
**ERROR! couldn't resolve module/action 'community.kubernetes.k8s'. This often indicates a misspelling, missing collection, or incorrect module path.**

The error appears to be in '/home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/main.yml': line 11, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Ensure the myapp Namespace exists.
      ^ here
```
EXPECTED RESULTS

Deploy my Kubernetes resources to my cluster

ADDITIONAL INFORMATION

I noticed that it states configured module search path = ['/home/user/.ansible/plugins/modules] but in my directory there is no plugins folder, in addition /usr/share/ansible directory does not exist

![image](https://user-images.githubusercontent.com/57595423/124125987-dd663a00-da82-11eb-821d-25ba684fe334.png)
![image](https://user-images.githubusercontent.com/57595423/124126004-e0f9c100-da82-11eb-8153-4a7e5dfcc038.png)

I also added in my ansible.cfg file the collections_path in order to resolve this problem but it did not work

```
[defaults]
inventory = /home/user/Desktop/Kubernetes/ansible-Examples/deploymentUsingPlaybook/inventory.yml
collections_paths = /home/user/.ansible/collections/ansible_collections
```

**Comment by gravesm** [comment]
@amin224 Your `collections_paths` in ansible.cfg should point to `~/.ansible/collections` not `~/.ansible/collections/ansible_collections`. If you want to set it through an environment variable you will need to use `ANSIBLE_COLLECTIONS_PATHS`.

I'll also add that the kubernetes collection requires ansible >=2.9.17. You will likely run into problems with your kubeconfig on older versions.

**Comment by amin224** [comment]
@gravesm Kindly note that I changed the path for collections_paths in my ansible.cfg to `~./ansible/collections` but I am still getting the same error.

The default ansible.cfg in my `/etc/ansible `directory
```

# config file for ansible -- https://ansible.com/
# ===============================================

# nearly all parameters can be overridden in ansible-playbook
# or with command line flags. ansible will read ANSIBLE_CONFIG,
# ansible.cfg in the current working directory, .ansible.cfg in
# the home directory or /etc/ansible/ansible.cfg, whichever it
# finds first

[defaults]

# some basic default values...

#inventory      = /etc/ansible/hosts
#library        = /usr/share/my_modules/
#module_utils   = /usr/share/my_module_utils/
#remote_tmp     = ~/.ansible/tmp
#local_tmp      = ~/.ansible/tmp
#plugin_filters_cfg = /etc/ansible/plugin_filters.yml
#forks          = 5
#poll_interval  = 15
#sudo_user      = root
#ask_sudo_pass = True
#ask_pass      = True
#transport      = smart
#remote_port    = 22
#module_lang    = C
#module_set_locale = False
```

- ansible-doc community.kubernetes

```
[WARNING]: module community.kubernetes not found in:
/home/user/.ansible/plugins/modules:/usr/share/ansible/plugins/modules:/usr/lib/python3/dist-packages/ansible/modules
```

Please note that when executing this command I noticed that the path is leading to `/usr/share/ansible` but in my `/usr/share `directory there is no ansible directory. Do i have to specify the library path in my `/etc/ansible/ansible.cfg` file?

> If you want to set it through an environment variable you will need to use `ANSIBLE_COLLECTIONS_PATHS`

Do you suggest that I should use this parameter in my playbook to work, because I added the collections parameter in my ansible-playbook but it did not resolve my issue.

```
- name: Deploy Kubernetes resources in Ansible Playbook
  hosts: localhost
  gather_facts: true
  become: true

  collections:
    - community.kubernetes

  tasks:

    - name: Ensure the myapp Namespace exists.
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: amintestingansible
        state: present
        register: namespace

    - debug: msg= "{{ namespace.stdout.split('\n') }}"
```

**Comment by amin224** [comment]
After uninstalling ansible and removing all ansible related directories, I tried a fresh installation of ansible using
```
$ sudo apt-add-repository --yes --update ppa:ansible/ansible
$ sudo apt install ansible
```

I have noticed that ansible does not create a plugins directory neither in `/home/amin/.ansible ` and no ansible directory in `/usr/share/` as stated in the configured module search path. @gravesm  **Do I have to create it manually?** If it can be changed in the `/etc/ansible/ansible.cfg` file Please tell me which parameter specifically.

```
ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/amin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```
