### ISSUE TITLE
helm module idempotency check failed when imagePullPolicy is Always

### ISSUE THREAD

**Issue by kakarukeys** [ansible-collections/kubernetes.core#165]
##### SUMMARY
when imagePullPolicy is Always, k8s always pulls the image regardless of identical tag.
so the idempotency check should compare SHA256 checksum of the images, otherwise it will report no difference when there is no change in values.
if this is too much to ask for, then the module should disregard the check results, and always run the helm upgrade command in this case.

##### ISSUE TYPE
- Bug Report

Not sure if this is a bug, or intended design. if this is intended, perhaps adding a new param to disable the check is welcome.

##### COMPONENT NAME
kubernertes.core.helm

##### ANSIBLE VERSION

```paste below
2.10.8
```

##### COLLECTION VERSION

```paste below
2.1.1
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT
Mojave 10.14.6
DigitalOcean Kubernetes 1.20

##### STEPS TO REPRODUCE

1. use the helm module to install any chart, with imagePullPolicy set to Always
2. update the docker image used in the chart, with no change in tag.
3. `helm diff upgrade --values values.yml <release> <chart>` shows no output
4. rerun the ansible command again.

##### EXPECTED RESULTS
it should perform helm upgrade, allowing k8s to pull the latest image.

##### ACTUAL RESULTS
it does not perform helm upgrade

**Comment by gravesm** [comment]
@kakarukeys Setting `force: true` should ignore the idempotency check and do what you want. Please let me know if this works for you.

**Comment by kakarukeys** [comment]
> @kakarukeys Setting `force: true` should ignore the idempotency check and do what you want. Please let me know if this works for you.

set `force: true` has a different meaning, it adds `--force` to the helm command. 
`--force                        force resource updates through a replacement strategy`
It has other implications, for example it would also replace the service, when there is no need to.
it's not equivalent to what I described.

**Comment by gravesm** [comment]
If you haven't changed anything in the chart or values, helm isn't going to redeploy anything. And unless something has changed in the pod spec or you are otherwise forcing kubernetes to restart the container, it's not going to do so. Maybe I'm misunderstanding what you are asking? Could you maybe provide the helm command that you would like to be run, and what the expected outcome of that command would be?

**Comment by kakarukeys** [comment]
I am seeing the helm command redeploys the pod sometimes. It may have something to do with the extra flags `--reset-values` and `--reuse-values`. But on a brand new release, it behaves as what you just said, so i will close this issue, since there's no deviation from this behavior in ansible helm module. 

I've added a random tag to force a redeploy as [stackoverflow suggests](https://stackoverflow.com/questions/53450759/helm-upgrade-install-isnt-picking-up-new-changes/55974926). Thank you for your help.
