### ISSUE TITLE
apis being overwritten in cluster_info

### ISSUE THREAD

**Issue by jmontleon** [ansible-collections/kubernetes.core#17]
##### SUMMARY
When I do this I seem to get one API per group:
```
    - name: Get APIs
      community.kubernetes.k8s_cluster_info:
      register: apis
```

I changed this: line
https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/modules/k8s_cluster_info.py#L209
to this and I get the full list of APIs:
`results[resource.kind + "." + resource.group] = {`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_cluster_info

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jason/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_COW_SELECTION(env: ANSIBLE_COW_SELECTION) = random
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT
Fedora 33

##### STEPS TO REPRODUCE
Run the above mentioned task and see that you have a list of one api per group when in many cases you should have several.

##### EXPECTED RESULTS
See all apis listed.

##### ACTUAL RESULTS
See a fraction of apis listed.

**Comment by goneri** [comment]
Just a note: If we change the behavior of the `cluster_info`, this will probably be a breaking change. And so we may have to wait for the 2.0.0 release.
