### ISSUE TITLE
release request current main branch as new version

### ISSUE THREAD

**Issue by itaru2622** [ansible-collections/kubernetes.core#193]
##### SUMMARY

release request current main branch as new version(2.1.2).
since 2.1.1 new features added, and I want to start using it

##### ISSUE TYPE
- release request current main branch as new version

##### ADDITIONAL INFORMATION
I know that main branch can be installed as follows.
it useful for testing  but it has potential risk for long term use.
so, I want to get  latest main branch features by usual install:

```
# install github main branch version
ansible-galaxy collection install git+https://github.com/ansible-collections/kubernetes.core.git,main

# usual install
ansible-galaxy collection install  kubernetes.core
```

**Comment by gravesm** [comment]
2.2.0 has been released.
