### ISSUE TITLE
I'd like to help out with writing tests.  Is there a specific area that tests would be wanted/needed?

### ISSUE THREAD

**Issue by cynthia-rempel** [ansible-collections/kubernetes.core#2]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

**Comment by geerlingguy** [comment]
We're not currently using this repository for maintenance, so for now I'm closing this issue (please see `community.kubernetes` instead).

**Comment by cynthia-rempel** [comment]
Followed the directions, and was told there wasn't a need.  I feel like my help isn't wanted.

**Comment by geerlingguy** [comment]
@cynthia-rempel - Please see my reply in the other issue :)
