### ISSUE TITLE
Different documentation on website

### ISSUE THREAD

**Issue by cortex3** [ansible-collections/kubernetes.core#206]
##### SUMMARY
The documentation file in this repository differs from what is displayed on the ansible website.
See for example the difference in the requirements section:
https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html#requirements

edit:
I've just noticed that the page appears to be identical to the one of the old module:
https://docs.ansible.com/ansible/latest/collections/community/kubernetes/k8s_module.html
which btw doesn't show that it is deprecated.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
kubernetes.core.k8s_module.rst

##### ANSIBLE VERSION
not relevant

**Comment by gravesm** [comment]
Hi @cortex3, sorry for the confusion. I'll try to clarify. The docs you find in this repo are for the currently developed main branch. The docs on docs.ansible.com are for the version that is packaged with the ansible community release--what you get when you install https://pypi.org/project/ansible/. The current version (ansible 4.4) contains the 1.2 branch of both this collection and the community.kubernetes collection. Ansible 5, which will be released later this fall, will contain the 2.x branch of both community.kubernetes and kubernetes.core. This version will also start giving deprecation warnings for the community.kubernetes namespace. The community.kubernetes 2.0 release will likely be the last release for that collection as it is just redirects to kubernetes.core. The community.kubernetes collection will also likely be removed in ansible 6. [A note about the deprecation status](https://github.com/ansible-community/ansible-build-data/blob/main/4/CHANGELOG-v4.rst#deprecated-features-2) of community.kubernetes went out in ansible 4.2.

I hope this helps clear things up. Let me know if you still have questions.

**Comment by cortex3** [comment]
Hi @gravesm,
thank you for the fast response and thank you for your work on this project.
My apologies I was not aware that this module is still shipped with ansible because of the banner at the top saying:
```
This plugin is part of the kubernetes.core collection (version 1.2.1).
To install it use: ansible-galaxy collection install kubernetes.core.
To use it in a playbook, specify: kubernetes.core.k8s.
```

I've installed the module via ansible-galaxy and had trouble setting it up because I wasn't aware of the new requirements.
I was trying to save others from having the same issue with this ticket but I guess that isn't easily possible.

If you don't mind I'll leave a bunch of error codes I received here in hopes of making this googleable for the next person running into this issue.

`  msg: kubernetes >= 12.0.0 is required`
```install_requires' must be a string or list of strings containing valid project/version requirement specifiers```
```    ImportError: No module named abc```

**Comment by gravesm** [comment]
I'm going to go ahead and close this. Feel free to reach out if you are still having problems.
