### ISSUE TITLE
k8s_cp does not delay module load

### ISSUE THREAD

**Issue by goneri** [ansible-collections/kubernetes.core#237]
##### SUMMARY

update: k8s_cp does not use the turbo mode at all.

Before `k8s_cp`'s main() is called, all the resources have to be loaded. This has an negative impact of the performance boost that we can get with turbo mode. Turbo mode works in two steps:

- regular: load the module, evaluate the parameters and send the module to the background daemon.
- in the background daemon: load the module and run the main() function.

The second steps should be fast because these dependencies are likely to be already in memory. We don't need most of k8s_cp.py during the first step. This content should be moved in a module_utils file that we lazy-load.

##### ISSUE TYPE
- Bug Report

**Comment by abikouo** [comment]
Thanks @goneri for the feedback, I will work on this one.
