### ISSUE TITLE
failure in k8s task when using a definition list should have better error message

### ISSUE THREAD

**Issue by jmazzitelli** [ansible-collections/kubernetes.core#28]
##### SUMMARY

Use a list in k8s definition list:
```
  set_fact:
    my_yaml_files: ["some.yaml", "another.yaml"]

  k8s:
     state: "present"
     namespace: "default"
    definition: |
      {% for mdy in my_yaml_files %}
      ---
      {{ lookup("template", mdy) }}
      ...
      {% endfor %}
```

If there is a syntax error in one of the templates (or simply that a resource in the list fails to be created), the error message that k8s spits out doesn't tell you WHICH item in the list fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION
2.9

##### STEPS TO REPRODUCE
See above.

##### EXPECTED RESULTS
An error message that better indicates which item in the list failed.
It might also be nice to have the rest of the items processed, but that might break the k8s design. As it is, if you have ANY error in ANY item in the list, the entire list of resources apparently fail to be persisted/created.

##### ACTUAL RESULTS
You do get an error, but all resources abort (fail to get created) so you aren't sure which item in the list caused the failure.

**Comment by abikouo** [comment]
this has been addressed in the following PR https://github.com/ansible-collections/kubernetes.core/pull/49
