### ISSUE TITLE
Support updating helm repositories 

### ISSUE THREAD

**Issue by skovbakke** [ansible-collections/kubernetes.core#281]
##### SUMMARY

The `kubernetes.core.helm_repository` module supports updating helm repositories, i.e. `helm repo update`. When a new version of a chart becomes available in a remote repository the local information about the repository is updated making the new version available for install.
 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

helm kubernetes.core.helm_repository 

##### ADDITIONAL INFORMATION

Currently, if a chart is available in a newer version or if a chart is added to a repository after that repository was added by the `helm_repository` moule, that helm chart will not be available for installation. This is because the local index of the helm repository is never updated after it is added. The only way to update the index (using the kubernetes.core.helm_repository module) is to delete it and add it again. 

The [`helm repo update`](https://helm.sh/docs/helm/helm_repo_update/) command is used to update local repository indices. The command, however, does not return information on whether any changes happened to the local index. 

Ideally the `helm repo update <repo_name>` command would run every time the module is invoked.

**Comment by gravesm** [comment]
@skovbakke The `helm` module has an `update_repo_cache` option which does what you are asking. Does this solve your problem, or is there another use case we should consider?

**Comment by skovbakke** [comment]
Yes, sorry, I must have missed that. That is exactly what I need.  Thank you!
