### ISSUE TITLE
kubernetes.core ships a binary without coresponding source

### ISSUE THREAD

**Issue by leegarrett** [ansible-collections/kubernetes.core#297]
##### SUMMARY
`molecule/default/roles/k8scopy/files/hello` is an unstripped go binary for x64_64, which does not come with source code, and does not have the corresponding build rules in place to build it. This unfortunately violates the GPLv3, and makes it undistributable by downstream distributions (in this case Debian).

It would be great to have it also be built by the build command in the Makefile, or have it replaced by something that is distributable. Removing it from the pypi package is also possible as a stop gap solution, but ideally it should ship with all code needed to use the collection, and run the tests, too.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`molecule/default/roles/k8scopy/files/hello`

##### STEPS TO REPRODUCE

```yaml
file molecule/default/roles/k8scopy/files/hello
molecule/default/roles/k8scopy/files/hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=hXQs3Sfk7BP_t5twMGGt/ApiAX9Vfh3MskyxKkiir/fnXuOf8gzVDDuIxFSv-d/HKCGoZO7tghIncxbx8SX, not stripped

```

##### EXPECTED RESULTS

Being able to build said binary from source, e.g. `make build`.

##### ACTUAL RESULTS

Only got the binary without source.

**Comment by Akasurde** [comment]
@abikouo Would you like to answer this? Thanks in advance

**Comment by gravesm** [comment]
I'm not sure there's a compelling reason to ship a binary at all. The only thing that binary is used for is to test whether or not k8s_cp can successfully transfer a binary file. Is there a reason we can't just generate random binary data during the molecule test and compare the hashes of the two files?
