### ISSUE TITLE
Helm Post Rendering support

### ISSUE THREAD

**Issue by gaborho** [ansible-collections/kubernetes.core#30]
##### SUMMARY
Helm Post Rendering support

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.kubernetes.helm

##### ADDITIONAL INFORMATION
Post rendering gives chart installers the ability to manually manipulate, configure, and/or validate rendered manifests before they are installed by Helm. It would be great to support this in the helm module. Use case would be to hand over a post renderer script (bash, python) what is execuring kustomize customization. More information: https://helm.sh/docs/topics/advanced/#post-rendering

**Comment by Prometej** [comment]
I am also interested in this feature. I would like to run kustomize in post-renderer. This is very useful if you need to make updates (usually security issues that are not covered in templating) on community charts without modifying them.

The links you provided are currently broken could you please update them?

**Comment by tima** [comment]
@Prometej I think ansible-collections/community.kubernetes#367 became #39 when the repo was migrated.

**Comment by akamac** [comment]
@Akasurde @tima it is a different feature. Post-rendering is not limited to kustomize, but rather can call any executable. This is a matter of exposing the `--post-renderer` flag in module args.

**Comment by Akasurde** [comment]
@akamac Would you be interested in opening a PR with your findings? Thanks in advance.
