### ISSUE TITLE
Create new tag to avoid "hello" binary

### ISSUE THREAD

**Issue by nkadel** [ansible-collections/kubernetes.core#301]
##### SUMMARY
The latest tag for kubernetes.core contains the "hello" compiled binary. That tag is used by antsibull to create the ansible-5.0.1 tarball, which winds up with this unwelcome and platform incompatible binary.

Updating the tag would allow antsibull to cmpile a cleaner and safer tarball.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core

##### ANSIBLE VERSION
ansible-5.0.1

```

**Comment by Akasurde** [comment]
FYI This binary is removed now via https://github.com/ansible-collections/kubernetes.core/pull/298. Release still pending.

**Comment by gravesm** [comment]
Release done.
