### ISSUE TITLE
Moving this content to kubernetes.core (v2.0)

### ISSUE THREAD

**Issue by tima** [ansible-collections/kubernetes.core#32]
Red Hat Ansible is looking to continue furthering this content collection for downstream applications and packaging. Continuing with the "community" prefix will be confusing and communicate and different status. To address this, this repo will be transferred to a new repo named kubernetes.core. The community.kubernetes collection/repo will remain, but all future development and activity will shift to the new repo. Eventually this repo will become a remapping to the content in kubernetes.core.

This migration will be part of the v2.0 development effort.

**Comment by geerlingguy** [comment]
@tima / @gravesm - It seems like the migration is ongoing at this point—just wondering, will there be a blog post we can reference for the move (especially considering it would be good to get a communique out to the Bullhorn newsletter, and ideally also through social channels (e.g. work with @gundalow to get it on Ansible Twitter, Reddit, etc.)?

**Comment by tima** [comment]
@geerlingguy It was in the last edition of The Bullhorn. We’re you looking for something more?

**Comment by geerlingguy** [comment]
I did see the mention; but I think a canonical blog post on the topic would be the best resource (IMO). Plus we could mention how popular the collection has been (still the most-downloaded by a large margin, I believe).

**Comment by gundalow** [comment]
Blog is a nice way to advertise this collections existence as well as having a clear call to action (easy ways to contribute, what the future may hold, how to test and what type of feedback we are looking for)

**Comment by tima** [comment]
This was mostly completed as part of 2.0. Closing it out.
