### ISSUE TITLE
Add an example to create a kubernetes.io/dockerconfigjson secret

### ISSUE THREAD

**Issue by ebarped** [ansible-collections/kubernetes.core#341]
##### SUMMARY
Add an example to create a kubernetes.io/dockerconfigjson secret

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
kubernetes.core.k8s

#### Description
I think that will be very valuable to the users to provide an example about how to create a k8s secret to allow kubelet download images from a registry.

Currently, im achieving this the "traditional" way:
```
- name: create secret
  shell: "kubectl -n doc create secret docker-registry mysecret --docker-server=myreg --docker-username=k8s --docker-password=\"{{mypassword}}\""
```

**Comment by abikouo** [comment]
Hi @ebarped 

Thanks for taking the time to report this issue.
Currently the kubernetes.core is not supporting specifically this feature, to do so you need to use the ``k8s`` module and manually create the definition of your secret. 
Something like 

```
- name: Create docker registry secret
  k8s:
     namespace: my-namespace
     definition:
       kind: "Secret",
       apiVersion: "v1",
       metadata:
           name: "my-secret"
       data:
           ".dockerconfigjson": "eyJhd9kVGRWWTJ4TlRVMHlOak5TWnkxZk9ISmFNVUpTZUc0dyJ9fX0="
       type: "kubernetes.io/dockerconfigjson"
```

The ``.dockerconfigjson`` should be created manually encoding credentials like the ones that could be found in ``~/.docker/config.json``
