### ISSUE TITLE
[DEPRECATION WARNING]: The 'return_code' return key is deprecated. Please use  'rc' instead.

### ISSUE THREAD

**Issue by erikgb** [ansible-collections/kubernetes.core#413]
##### SUMMARY
It seems like this deprecation warning is emitted - even if all usage is migrated to `rc`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`kubernetes.core.k8s_exec`

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.11 (main, Mar 18 2022, 16:45:24) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.9/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.0
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(env: ANSIBLE_LOAD_CALLBACK_PLUGINS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = auto
```

##### OS / ENVIRONMENT

Debian-flavoured container image from based on official python image.

##### STEPS TO REPRODUCE

```yaml
  kubernetes.core.k8s_exec:
    pod: <pod-name>
    container: <container-name>
    command: <some command>
  register: command_status
  retries: 7
  delay: 3
  until: command_status.rc == 0
```

##### EXPECTED RESULTS

Task runs successfully, with no warnings.

##### ACTUAL RESULTS

```paste below
[DEPRECATION WARNING]: The 'return_code' return key is deprecated. Please use 
'rc' instead. This feature will be removed from kubernetes.core in version 
4.0.0. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

**Comment by Akasurde** [comment]
@erikgb Thanks for reporting this issue. Due to Ansible Core engine changes, we moved from `return_code` to `rc`. We need to provide deprecation warnings to the user as per Ansible Development Guidelines. You may want to disable this warning by using `deprecation_warnings=False` in ansible.cfg. Apart from that, I do not have any other solution on top of my head right now. 

@tima @gravesm @abikouo What do you think about this? 

Thanks.

**Comment by gravesm** [comment]
We have no way to know what fields of the return value are used, or even if the return value is used at all. This is a limitation of Ansible and there's not much we can do about this. As a general rule, we issue warnings for any breaking changes for a period of time before the breaking change is made.

**Comment by erikgb** [comment]
Here is a suggestion, but it might need some adjustments since I am not native in English. 😅 

````
[DEPRECATION WARNING]: The 'return_code' return key is renamed to 'rc'.
To allow users to migrate to the new name, both keys are returned for now.
Old name ('return_code') will be removed from kubernetes.core in version 4.0.0.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
````

I also found this feature idea, that could have mended this: https://github.com/ansible/ansible/issues/49900.
