### ISSUE TITLE
kubernetes.core.helm supports OCI repositories

### ISSUE THREAD

**Issue by jbuamw** [ansible-collections/kubernetes.core#429]
##### SUMMARY
Hi Everyone, 
have you consider to support helm charts deployment from OCI-based registries by kubernetes.core.helm component?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
kubernetes.core.helm

**Comment by rossbachp** [comment]
How I can handle a Azure AZR helm registry

**Comment by yajo** [comment]
FWIW the docs are [here](https://helm.sh/docs/topics/registries/).

**Comment by jbuamw** [comment]
I can confirm it works with `chart_ref` as shown above. The issue can be closed.

**Comment by grantral** [comment]
I think this feature should be added to the docs because it is not intuitive.

```
chart_reference on chart repository.
ADD: path to a OCI registry.
path to a packaged chart.
path to an unpacked chart directory.
absolute URL.
Required when release_state is set to present.
```
