### ISSUE TITLE
Previous log support

### ISSUE THREAD

**Issue by jeason81** [ansible-collections/kubernetes.core#437]
##### SUMMARY
The `k8s_log` module is missing support for the `previous` parameter. The `kubectl logs --previous <pod>` command allows for the retrieval of the previously terminated pods logs which is useful in troubleshooting.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
k8s_log

##### ADDITIONAL INFORMATION
I've submitted a pull request that adds support for this parameter. Output and functionality are identical.
#436

**Comment by abikouo** [comment]
fixes by #436
