### ISSUE TITLE
k8s_cp state=from_pod requires 'find' binary to be present on the remote pod

### ISSUE THREAD

**Issue by samene** [ansible-collections/kubernetes.core#486]
##### SUMMARY
Using the k8s_cp module with state=from_pod requires the `find` command to be present on the remote pod. With newer base docker images like openjdk:17 there is no find command on them. This requirement is also not stated in the documentation.

The code in `plugins/module_utils/copy.py` uses `find` to list files if the remote path is a folder. However this is not needed if it is a file and not a folder. 

There should be a better way to list the files in a folder without relying on OS binaries. Or there could be an argument like `isDir: true` if the file being copied is a folder or not.

**Comment by gravesm** [comment]
@samene Thanks, we'll look into a fix for this.
