### ISSUE TITLE
k8s: state=created

### ISSUE THREAD

**Issue by ooraini** [ansible-collections/kubernetes.core#496]
##### SUMMARY

Create an object only if it doesn't already exist relying on the HTTP verb POST(or the create method/function).

```
Determines if an object should be created, patched, or deleted. When set to present, an object will be created, if it does not already exist. If set to absent, an existing object will be deleted. If set to present, an existing object will be patched, if its attributes differ from those specified using resource_definition or src.

patched state is an existing resource that has a given patch applied. If the resource doesn’t exist, silently skip it (do not raise an error).
created state will create the object if it doesn't exit. Unlike state present, the object will NOT be modified if it already exists. No error will be returned if the object exists.
```

This can be implemented in two tasks by checking if the object already exists and only creating it if it doesn't exits. This has two disadvantages, 1) two tasks. 2) not atomic(unlikely to matter).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by goneri** [comment]
Thank you for the suggestion. We prefer to keep the current semantic for the sack of simplicity.

**Comment by vitalyu** [comment]
@goneri it's not about simplicity! it's important in creating leases for example, to ensure only one acquired the lock
