### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by anshulbehl** [ansible-collections/kubernetes.core#5]
##### SUMMARY

Both redhat.openshift and kubernetes.core collections are missing requirements.txt file in the collection.
Files are needed to create a certified execution environment that include both of the certified collections. I am not sure which is the correct place to file this bug , so I am taking a best guess. Please correct me if I am wrong @tima @gravesm @Akasurde

**Comment by gravesm** [comment]
@anshulbehl Sorry for the delay. I published a new version of redhat.openshift to AH yesterday with the fix. Looks like it's still waiting for approval but once it's approved both collections should have a requirements.txt file.
