### ISSUE TITLE
Install the Fabric Operations Console and the Fabric Operator failed with msg: "kubernetes >= 12.0.0 is required"

### ISSUE THREAD

**Issue by wwkicq1234** [ansible-collections/kubernetes.core#501]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by gravesm** [comment]
You need to install https://github.com/kubernetes-client/python. If you are still having problems please provide the requested information and reopen.
