### ISSUE TITLE
add filter documentation

### ISSUE THREAD

**Issue by samccann** [ansible-collections/kubernetes.core#524]
##### SUMMARY

ansible-core 2.14 adds 'side car docs' which gives collection owners the ability to add documentation for previously undocumentable filter and test plugins.

This requires creating yaml files in the same directory as the filter or test plugin code, one yaml file per plugin.

See https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/b64decode.yml for an example.
Please add filter docs for 
[k8s_config_resource_name filter](https://docs.ansible.com/ansible/devel/collections/kubernetes/core/k8s_config_resource_name_filter.html#ansible-collections-kubernetes-core-k8s-config-resource-name-filter) –

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```
Related to https://github.com/ansible-community/community-team/issues/65

**Comment by abikouo** [comment]
closed by #559
