### ISSUE TITLE
Documentation of default kubeconfig location

### ISSUE THREAD

**Issue by ishigoya** [ansible-collections/kubernetes.core#53]
##### SUMMARY

References to the location of the default kubeconfig file are not consistent. In some places, it's `~/.kube/config`, and in others it's `~/.kube/config.json`.

I think `~/.kube/config` is correct; as listed in the [kubernetes docs](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/),  and judging by the behaviour of the module.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

From `$ grep -R kube/config` in the git repository master:

![20210410_21h04m55s_grim](https://user-images.githubusercontent.com/16798645/114269322-6d2ab800-9a41-11eb-84fa-f7d93cc9e427.png)

##### ANSIBLE VERSION
Present on [2.10 documentation](https://docs.ansible.com/ansible/2.10/collections/community/kubernetes/k8s_module.html) page

```paste below

```

**Comment by gravesm** [comment]
@ishigoya Thank you for reporting this.

**Comment by Akasurde** [comment]
resolved_by_pr #65
