### ISSUE TITLE
kubernetes.core.helm module does not support Helm install commands --set-file

### ISSUE THREAD

**Issue by sandipchitale** [ansible-collections/kubernetes.core#533]
##### SUMMARY
kubernetes.core.helm module does not support Helm install commands --set-file

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.helm

##### ANSIBLE VERSION

```
ansible --version
ansible [core 2.13.3]
  config file = /home/vncuser/schitale_linux/IA/tools/ansible/infoarchive-lab-deployment/ansible.cfg
  configured module search path = ['/home/vncuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/vncuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Jun 24 2022, 15:32:51) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below
ansible-galaxy collection list kubernetes.core 

# /usr/lib/python3.9/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.2  
```

##### STEPS TO REPRODUCE

I want to use equivalent of [--set-file](https://helm.sh/docs/helm/helm_install/#options) option of ```helm install``` command to set the values of properties from file while installing a Helm chart using the kubernetes.core.helm . I see only the ```release_values``` and ```values_file``` options.

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by abikouo** [comment]
closed by #546
