### ISSUE TITLE
Missing documentation for kubernetes.core.k8s_config_resource_name 

### ISSUE THREAD

**Issue by lucab85** [ansible-collections/kubernetes.core#558]
##### SUMMARY

Missing documentation or could not parse documentation: No documentation available for the `kubernetes.core.k8s_config_resource_name` Filter Plugin

[doc page reference](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_config_resource_name_filter.html#ansible-collections-kubernetes-core-k8s-config-resource-name-filter)

The documentation for the filter plugin, kubernetes.core.k8s_config_resource_name, was malformed.

The errors were:

Missing documentation or could not parse documentation: No documentation available for kubernetes.core.k8s_config_resource_name (/tmp/tmpe67f__85/installed/ansible_collections/kubernetes/core/plugins/filter/k8s.py)

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
`k8s_config_resource_name` Filter Plugin

##### ANSIBLE VERSION

```paste below
ansible --version
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/Users/lberton/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/6.6.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/lberton/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.9 (main, Dec 15 2022, 10:44:50) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by abikouo** [comment]
@lucab85 Thanks for raising this issue, it seems parsing filter plugins is a new feature with ansible 2.14.
I have created a pull request to fix that issue.
