### ISSUE TITLE
kubernetes.core.k8s-xxx need remote node has kubernetes module installed

### ISSUE THREAD

**Issue by willzhang** [ansible-collections/kubernetes.core#581]
##### SUMMARY

kubernetes.core.k8s-xxx need remote node has kubernetes module installed.

is it possible not require remote node has kubernetes module installed, because it's hard in offline environment.

for ubuntu server 22.04 LTS, the apt repository and pip repository is need for offline environment.
```
apt install -y python3-pip
pip install kubernetes
```

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml
TASK [../roles/kubernetes-apps/kubevirt : addons | apply kubevirt operator yamls] ***************************************************************************************************
fatal: [node1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (kubernetes) on node1's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by gravesm** [comment]
This is not something we can do anything about as this is simply how Ansible works. Third party dependencies have to be present on the remote node for any modules that have those dependencies.
