### ISSUE TITLE
2.5.0 ?

### ISSUE THREAD

**Issue by katarzynainit** [ansible-collections/kubernetes.core#650]
##### SUMMARY
When do you plan to release 2.5.0 version?

##### ISSUE TYPE
Awaiting some features I found already implemented

##### COMPONENT NAME
kubernetes.core.helm

**Comment by jillr** [comment]
Hi @katarzynainit  The next release is being planned for in the next month and will be 3.0.0, as it will have new anisble-core version requirements.
