### ISSUE TITLE
Allow Setting Helm Timeout Independent of Wait

### ISSUE THREAD

**Issue by atreides322** [ansible-collections/kubernetes.core#67]
For the Helm module, the `wait_timeout` provides the the `--timeout` argument to the helm command:

https://github.com/ansible-collections/community.kubernetes/blob/f99614370c4fd3457dbcf9581217df7997ba86fd/plugins/modules/helm.py#L343-L346

However, the `--timeout` argument also effects Helm independently of `--wait`. It can be used to specify a timeout for all Kubernetes commands. https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback

I am running into issues where pre-chart hooks can sometimes take longer than default five minutes to execute, but I can't change the timeout, because `wait_timeout` is ignored if `wait` is not `True`. I can't add `wait: yes`,  because it is a legacy app and it takes a consider amount of time for all the pods to enter a ready state, which Helm would wait for.

**Comment by Akasurde** [comment]
@atreides322 Thanks for reporting this issue.

**Comment by Akasurde** [comment]
Let me check this and get back to you. btw, how are you invoking this chart using the command line?

**Comment by atreides322** [comment]
If I'm using the command line, then I am doing something like `helm install --timeout 10m chart name`.

If it helps, I created a very contrived demo: https://github.com/atreides322/ansible-helm-timeout-demo
