### ISSUE TITLE
kubernetes.core.helm handling of CRDs

### ISSUE THREAD

**Issue by lukapetrovic-git** [ansible-collections/kubernetes.core#713]
##### SUMMARY
The question regards the kubernetes.core.helm module and its handling of CRDs. I could not find information about it.

How does **kubernetes.core.helm** handle CRDs, i.e. what happens if **skip_crds: false**?
Is the handling of CRDs the same as with "plain" helm where there is no support for upgrading CRDs, just initially installing them?

I was not sure where to ask this question or how to categorize it, so excuse me if this is not the right place. :smile: 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
kubernetes.core 3.0.0
kubernetes.core.helm module

##### ANSIBLE VERSION
```
ansible [core 2.16.6]
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

**Comment by yurnov** [comment]
Please find source code of `kubernetes.core.helm` module [here](https://github.com/ansible-collections/kubernetes.core/blob/main/plugins/modules/helm.py#L566) to find the answer to your question.

So, `skip_crds` is full equivalent of `--skip-crds` to helm command, and generally speaking, module just constructs and execute the helm command, so, behavior for crd or anything else is the same as `helm` command in cli

**Comment by lukapetrovic-git** [comment]
That makes complete sense, thanks for the response! 🙂

**Comment by yurnov** [comment]
Hi @lukapetrovic-git,

is your question answered?

**Comment by lukapetrovic-git** [comment]
Yes, thanks again, just forgot to close.
