### ISSUE TITLE
Issues tab under community.kubernetes is gone - together with all info in the issues

### ISSUE THREAD

**Issue by valkolaci** [ansible-collections/kubernetes.core#748]
##### SUMMARY
I'm cheating here because this should be an issue on community.kubernetes. However, since the bug is the very lack of the Issues section there, it's not possible to file this report there.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
GitHub repo Issues section

Since the migration to the current repo from [community.kubernetes](https://github.com/ansible-collections/community.kubernetes), someone has changed the Issues section of the old repo to be hidden, rendering all knowledge in those issues inaccessible.

As there are links to those pieces of information all around the Internet, currently these links are 404. Ie: [Forum](https://groups.google.com/g/awx-project/c/OCs2iotXBYY/m/WfEgd2JFAQAJ)

**Comment by gravesm** [comment]
I have re-enabled issues on the community.kubernetes repo for archival purposes.
