### ISSUE TITLE
Noob-Question: Openshift 4.15 howto start ?

### ISSUE THREAD

**Issue by n00bsi** [ansible-collections/kubernetes.core#773]
Hi,
how to start ?
Have a OpenShift Cluster.
Got the .kube/config file.
Wanna connect to the Cluster to get may be the Version, Pods etc.
But is there no file Bundle to download and extract
add the path to the kube-config file or user and password to run the frist action may be check the cluster_version ?

**Comment by rabin-io** [comment]
Simple as 

```
export KUBECONFIG=~/.kube/config
oc get node
oc get clusterVersion
```

**Comment by gravesm** [comment]
This would be more appropriate for the [Ansible forum](https://forum.ansible.com/).
