### ISSUE TITLE
Server-side apply support

### ISSUE THREAD

**Issue by akamac** [ansible-collections/kubernetes.core#87]
##### SUMMARY
It would be great if `k8s` module supported server-side apply.
https://kubernetes.io/docs/reference/using-api/server-side-apply/
https://kubernetes.io/blog/2020/04/01/kubernetes-1.18-feature-server-side-apply-beta-2/

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`k8s` module

**Comment by roelarents** [comment]
I suppose one of the requirements is for the k8s python client to support it. An issue for that has been made here: 
https://github.com/kubernetes-client/python/issues/1430

**Comment by abikouo** [comment]
Waiting for approval on k8s python client.
https://github.com/kubernetes-client/python-base/pull/254

**Comment by akamac** [comment]
I see it's been merged :)

**Comment by abikouo** [comment]
Yes but not yet released
