### ISSUE TITLE
k8s module documentation has missing google.auth requirement

### ISSUE THREAD

**Issue by ffirg** [ansible-collections/kubernetes.core#94]
##### SUMMARY
k8s module documentation has missing google.auth requirement

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
k8s_module docs - https://docs.ansible.com/ansible/latest/collections/community/kubernetes/k8s_module.html

##### ANSIBLE VERSION

```
ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/phil/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Comment by gravesm** [comment]
@ffirg could you provide the specific error message you are getting? google-auth is not directly required by the module, but it is a transitive dependency through openshift and the kubernetes client. Could you report what version of the kubernetes client you have installed?

**Comment by Akasurde** [comment]
@ffirg `google.auth` is a requirement of `kubernetes` Client Python and not of `kubernetes.core` collection. Like @gravesm said it is a transitive dependency. Let me know your views on this. Thanks.

**Comment by Akasurde** [comment]
I will go ahead and close this issue. Thanks.
