### ISSUE TITLE
Bad name

### ISSUE THREAD

**Issue by mcandre** [ansible-collections/kubernetes.core#95]
##### SUMMARY

Don't call this the "Kubernetes" collection when in fact it only works for specifically OpenShift Kubernetes clusters, not regular Kubernetes clusters. This is misleading and confuses users.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

The collection.

##### ACTUAL RESULTS

**Comment by gravesm** [comment]
@mcandre Is there a specific problem you are having? This module will work with and is tested against a regular kubernetes cluster.

**Comment by Akasurde** [comment]
@mcandre Openshift clusters can be managed using `redhat.openshift` and OKD clusters are managed by `community.okd`. So your assumption may not be right.

**Comment by Akasurde** [comment]
I will go ahead and close this issue. Please feel free to comment or open a new issue.
